### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by kheirif** [lmullen/dh-r#17]
When I ran the codes placed here:
I got the following error:

> places <- texts_annotated %>%
> - lapply(entities, kind = "location")
>   Show Traceback

 Rerun with Debug
 Error in substring(x, i$start, i$end) : invalid substring arguments 
Error in match.fun(FUN) : argument "FUN" is missing, with no default

**Here is my sessionInfo()**
sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.5 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] magrittr_1.5  RWeka_0.4-24  openNLP_0.2-5 NLP_0.1-8     rJava_0.9-8  

loaded via a namespace (and not attached):
[1] openNLPdata_1.5.3-2 tools_3.2.3         grid_3.2.3  
[4] RWekajars_3.7.12-1

**Comment by lmullen** [comment]
I re-ran this code and got no error message. Looking at your error message it is possible that you have not defined the function `entities()` which actually extracts the place names. Are you sure that you have run all the code from the beginning of the chapter?
