### ISSUE TITLE
Unclear where historydata package comes from in "Data Manipulation"

### ISSUE THREAD

**Issue by gregjp48** [lmullen/dh-r#19]
Since readers might not approach the book linearly (and chapters may be excerpted), it may be helpful to link back to that part of the introduction.

**Comment by lmullen** [comment]
@gregjp48 Thanks for the suggestion. I'm guessing your taking Ryan Cordell's course and are looking at the old version of the site? In the new version there will be a chapter (not yet written) called "Getting started" where I will do exactly as you suggest. Please do let me know if you have other thoughts.

http://dh-r.lincolnmullen.com/

**Comment by palermog** [comment]
Yup, that's right! Glad to provide feedback and chat about the book, since textbook rhetoric (especially of scientific/technical books) is an underdeveloped interest of mine.

This is actually an old account, so I'll post any additional suggestions from the new one I created for the course.
